name: food_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  local_storage:
    path: ../../data/local_storage
  domain_model:
    path: ../../domain_model
  rxdart: ^0.27.7
dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/