name: food_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  cache_storage:
    path: ../../data/cache_storage
  domain_model:
    path: ../../domain_model

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
