name: authentication_repository
description: Flutter package which manages the authentication domain.
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  cafebazaar_auth: ^1.0.4
  cafebazaar_flutter: ^1.0.2
environment:
  sdk: ">=3.0.0 <4.0.0"