name: domain_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  ionicons: ^0.2.2

  local_storage: 
    path: ../data/local_storage
  formz: ^0.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
