name: Android Release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
